# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zcrypt < Formula
  desc "Private cloud storage that costs less — terminal client"
  homepage "https://zcrypt.cloud"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Wosmos/zcrypt/releases/download/v0.1.0/zcrypt_0.1.0_darwin_amd64.tar.gz"
      sha256 "a36001c9a52a678772fa4024a11e55899438e63fa70d9742e4b37e5f76cf901a"

      define_method(:install) do
        bin.install "zcrypt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Wosmos/zcrypt/releases/download/v0.1.0/zcrypt_0.1.0_darwin_arm64.tar.gz"
      sha256 "1a360b16b08d1fc35b98bc1d44213d91e52e0a36f92826b71dcc30bda60093e4"

      define_method(:install) do
        bin.install "zcrypt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Wosmos/zcrypt/releases/download/v0.1.0/zcrypt_0.1.0_linux_amd64.tar.gz"
      sha256 "4940e6065e00ddd1da424f3b4b2175337f19753d482ef13a03fa9a9b48a7102a"
      define_method(:install) do
        bin.install "zcrypt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Wosmos/zcrypt/releases/download/v0.1.0/zcrypt_0.1.0_linux_arm64.tar.gz"
      sha256 "5985545d6e8729c1fb75b0ba24d62be7180ef5b77a19491e7301f700fbed49ad"
      define_method(:install) do
        bin.install "zcrypt"
      end
    end
  end

  test do
    system "#{bin}/zcrypt", "--version"
  end
end
